-- Database Schema for Nexus Studio
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- Table for user profiles
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY,
  username text UNIQUE NOT NULL,
  email text UNIQUE NOT NULL,
  password text NOT NULL,
  full_name text,
  bio text,
  location text,
  expertise text[],
  avatar_url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table for projects
CREATE TABLE public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  image_url text,
  category text,
  tags text[],
  owner_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status text DEFAULT 'active',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Disable RLS for backend management
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects DISABLE ROW LEVEL SECURITY;

-- Storage policies for project-assets
DROP POLICY IF EXISTS "project-assets images are publicly accessible." ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload project assets" ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own assets" ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own assets." ON storage.objects;

CREATE POLICY "project-assets images are publicly accessible." ON storage.objects FOR SELECT USING (bucket_id = 'project-assets');
CREATE POLICY "Authenticated users can upload project assets" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'project-assets');
CREATE POLICY "Users can update their own assets" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'project-assets' AND auth.uid() = owner);
CREATE POLICY "Users can delete their own assets." ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'project-assets' AND auth.uid() = owner);
